#!/usr/bin/env python3
"""Tests for the PT 7.3.0 agent capabilities manifest CLI."""

from __future__ import annotations

import json
import subprocess
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CAPABILITIES = ROOT / "bin" / "pt730-capabilities"


class CapabilitiesCliTest(unittest.TestCase):
    def run_cmd(self, *args: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [str(CAPABILITIES), *args],
            cwd=ROOT.parent,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=30,
            check=False,
        )

    def test_default_output_is_machine_readable_manifest(self) -> None:
        result = self.run_cmd()
        self.assertEqual(result.returncode, 0, result.stderr)
        data = json.loads(result.stdout)
        self.assertEqual(data["packet_tracer_version"], "7.3.0")
        self.assertIn("pt730-layout", data["offline_tools"])
        self.assertIn("pt730-compose", data["offline_tools"])
        self.assertIn("pt730-mcp", data["offline_tools"])
        self.assertIn("pt730-config-plan", data["offline_tools"])
        self.assertIn("pt730-ip-plan", data["offline_tools"])
        self.assertIn("pt730-render", data["offline_tools"])
        self.assertIn("pt730-models", data["offline_tools"])
        self.assertIn("pt730-pipeline", data["offline_tools"])
        self.assertIn("pt730-ios-template", data["offline_tools"])
        self.assertIn("pt730-lab", data["offline_tools"])
        self.assertIn("pt730-safety", data["offline_tools"])
        self.assertIn("pt730-template", data["offline_tools"])
        self.assertIn("pt730-topo", data["live_tools"])
        self.assertIn("dhcpRun(", data["blocked_patterns"])
        self.assertIn("schema", data["ios_template_features"])
        self.assertIn("routed_interfaces", data["ios_template_features"])
        self.assertIn("spanning_tree", data["ios_template_features"])
        self.assertIn("etherchannel", data["ios_template_features"])
        self.assertIn("dhcp_relay", data["ios_template_features"])
        self.assertIn("hsrp", data["ios_template_features"])
        self.assertIn("ios_dhcp_server", data["ios_template_features"])
        self.assertIn("ntp_client", data["ios_template_features"])
        self.assertIn("syslog_client", data["ios_template_features"])
        self.assertIn("snmp", data["ios_template_features"])
        self.assertIn("ospf", data["ios_template_features"])
        self.assertIn("spanning_tree", data["query_summary_fields"])
        self.assertIn("etherchannel", data["query_summary_fields"])
        self.assertIn("dhcp_helpers", data["query_summary_fields"])
        self.assertIn("hsrp", data["query_summary_fields"])
        self.assertIn("ios_dhcp_pools", data["query_summary_fields"])
        self.assertIn("ntp", data["query_summary_fields"])
        self.assertIn("syslog", data["query_summary_fields"])
        self.assertIn("snmp", data["query_summary_fields"])
        self.assertIn("l3_svis", data["config_plan_features"])
        self.assertIn("ospf", data["config_plan_features"])
        self.assertIn("static_routes", data["config_plan_features"])
        self.assertIn("config_file_export", data["config_plan_features"])
        self.assertIn("core_interconnect_pool", data["compose_features"])
        self.assertIn("campus", data["pipeline_features"])
        self.assertIn("ospf_routing", data["pipeline_features"])
        self.assertIn("config_file_export", data["pipeline_features"])
        self.assertIn("drawio_render", data["pipeline_features"])
        self.assertIn("template_lab_bundle", data["lab_features"])
        self.assertIn("plan_lab_bundle", data["lab_features"])
        self.assertIn("lab_report_markdown", data["lab_features"])
        self.assertIn("report_render_preset", data["lab_features"])
        self.assertIn("verification_plan_artifacts", data["lab_features"])
        self.assertIn("single_spec_input", data["lab_features"])
        self.assertIn("custom_plan_input", data["lab_features"])
        self.assertIn("config_file_export", data["lab_features"])
        self.assertIn("drawio", data["render_features"])
        self.assertIn("diagram_audit", data["render_features"])
        self.assertIn("verification_plan_json", data["render_features"])
        self.assertIn("verification_plan_markdown", data["render_features"])
        self.assertIn("render_bundle", data["render_features"])
        self.assertIn("bundle_manifest", data["render_features"])
        self.assertIn("visual_themes", data["render_features"])
        self.assertIn("report_render_preset", data["render_features"])
        self.assertIn("visible_titles", data["render_features"])
        self.assertIn("diagram_legends", data["render_features"])
        self.assertIn("link_label_toggle", data["render_features"])
        self.assertIn("model_label_toggle", data["render_features"])
        self.assertIn("visual_group_boxes", data["render_features"])
        self.assertIn("wireless_ap_icons", data["render_features"])
        self.assertIn("wireless_link_styling", data["render_features"])
        self.assertIn("ap_config_summary", data["render_features"])
        self.assertIn("vlan_config_summary", data["render_features"])
        self.assertIn("router_dhcp_pool_summary", data["render_features"])
        self.assertIn("security_policy_summary", data["render_features"])
        self.assertIn("lan_star", data["template_features"])
        self.assertIn("wireless_lan", data["template_features"])
        self.assertIn("vlan_router_on_stick", data["template_features"])
        self.assertIn("switching_lab", data["template_features"])
        self.assertIn("server_services", data["template_features"])
        self.assertIn("edge_security", data["template_features"])
        self.assertIn("ospf", data["template_features"])
        self.assertIn("dhcp_client_hosts", data["template_features"])
        self.assertIn("server_dhcp", data["template_features"])
        self.assertIn("router_dhcp_pools", data["template_features"])
        self.assertIn("wireless_access_points", data["template_features"])
        self.assertIn("laptop_clients", data["template_features"])
        self.assertIn("ssid_metadata", data["template_features"])
        self.assertIn("dot1q_subinterfaces", data["template_features"])
        self.assertIn("trunk_ports", data["template_features"])
        self.assertIn("access_vlan_ports", data["template_features"])
        self.assertIn("dmz_servers", data["template_features"])
        self.assertIn("nat_overload", data["template_features"])
        self.assertIn("outside_acl", data["template_features"])
        self.assertIn("router_ring", data["template_features"])
        self.assertIn("wan_ring", data["template_features"])
        self.assertIn("campus", data["template_features"])
        self.assertIn("redundant_campus", data["template_features"])
        self.assertIn("enterprise_edge", data["template_features"])
        self.assertIn("hq_vlans", data["template_features"])
        self.assertIn("branch_wan", data["template_features"])
        self.assertIn("isp_internet", data["template_features"])
        self.assertIn("campus_l3_configs", data["template_features"])
        self.assertIn("dual_core", data["template_features"])
        self.assertIn("dual_homed_access", data["template_features"])
        self.assertIn("etherchannel", data["template_features"])
        self.assertIn("portfast_bpduguard", data["template_features"])
        self.assertIn("hsrp_gateways", data["template_features"])
        self.assertIn("dhcp_relay", data["template_features"])
        self.assertIn("ntp_syslog_snmp", data["template_features"])
        self.assertIn("site_lans", data["template_features"])
        self.assertIn("server_dns", data["template_features"])
        self.assertIn("ospf", data["template_features"])
        self.assertIn("server_tftp", data["template_features"])
        self.assertIn("tools_call", data["mcp_features"])
        self.assertIn("schema_wrappers", data["mcp_features"])
        self.assertIn("render_bundle_wrapper", data["mcp_features"])
        self.assertIn("verification_plan_wrapper", data["mcp_features"])
        self.assertIn("lab_bundle_wrapper", data["mcp_features"])
        self.assertIn("lab_plan_wrapper", data["mcp_features"])
        self.assertIn("lab_report_wrapper", data["mcp_features"])
        self.assertIn("template_option_wrappers", data["mcp_features"])
        self.assertIn("workflow_option_wrappers", data["mcp_features"])
        self.assertIn("layout_option_wrappers", data["mcp_features"])
        self.assertIn("config_export_option_wrappers", data["mcp_features"])
        self.assertIn("catalog_wrappers", data["mcp_features"])
        self.assertIn("safety_js_wrappers", data["mcp_features"])
        self.assertIn("allow_live_gated_live_tools", data["mcp_features"])
        self.assertIn("allow_live_gated_device_tools", data["mcp_features"])
        self.assertIn("write_gated_model_records", data["mcp_features"])
        self.assertIn("topo_query_export_wrappers", data["mcp_features"])
        self.assertIn("model_registry_wrappers", data["mcp_features"])
        self.assertIn("live_lifecycle_dry_run", data["mcp_features"])
        self.assertIn("live_eval_dry_run", data["mcp_features"])
        self.assertIn("live_smoke_dry_run", data["mcp_features"])
        self.assertIn("live_apply_dry_run", data["mcp_features"])
        self.assertIn("live_device_dry_run", data["mcp_features"])
        self.assertIn("live_pc_dhcp_dry_run", data["mcp_features"])
        self.assertIn("live_server_service_dry_run", data["mcp_features"])
        self.assertIn("live_server_account_config_dry_run", data["mcp_features"])
        self.assertIn("live_ftp_dry_run", data["mcp_features"])
        self.assertIn("live_sim_dry_run", data["mcp_features"])
        self.assertIn("pt-reverse/bin/pt730-template lan-star --pcs 4 --servers 1 --network 192.168.10.0/24", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-template wireless-lan --aps 2 --laptops 4 --servers 1 --ssid PT730-LAB --network 192.168.80.0/24", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-template vlan-router-on-stick --vlans 3 --hosts-per-vlan 2 --servers-per-vlan 1 --native-vlan 10", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-template vlan-router-on-stick --vlans 3 --hosts-per-vlan 2 --servers-per-vlan 1 --client-addressing dhcp", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-template switching-lab --vlans 3 --hosts-per-vlan 2 --access-switches 2", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-template server-services --clients 3 --services all --domain services.local", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-template edge-security --inside-hosts 3 --dmz-servers 2 --internet-hosts 1 --domain edge.local", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-template router-ring --routers 4 --interconnect-pool 10.20.0.0/28", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-template wan-ring --sites 3 --hosts-per-site 2 --servers-per-site 1 --routing ospf", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-template campus --cores 2 --segments 4 --hosts-per-segment 2 --servers 4 --l3 --routing ospf", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-template redundant-campus --segments 4 --hosts-per-segment 2 --servers 4 --routing ospf", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-template enterprise-edge --campus-vlans 3 --branches 2 --dmz-servers 2 --routing ospf", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-lab template <lab-spec.json> --output-dir <out-dir>", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-lab plan <plan.json> --output-dir <out-dir> --basename topology --formats svg,drawio,html,markdown,summary,diagram-audit --title <title> --legend", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-lab plan <plan.json> --output-dir <out-dir> --basename topology --preset report", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-lab report <out-dir>/manifest.json --output <out-dir>/deliverable.md", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-pipeline campus --ip-plan <ip-plan.json> --compose-spec <campus-spec.json> --output-dir <out-dir> --routing ospf", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-layout <plan.json> --output <layout.json>", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-compose campus <campus-spec.json> --output <plan.json>", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-config-plan campus <plan.json> --output <configured-plan.json>", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-config-plan campus <plan.json> --l3 --routing rip --output <configured-plan.json>", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-config-plan campus <plan.json> --l3 --routing ospf --output <configured-plan.json>", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-config-plan campus <plan.json> --l3 --routing static --output <configured-plan.json>", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-config-plan export-configs <configured-plan.json> --output-dir <configs-dir>", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-ip-plan campus <ip-plan.json> --output <planned-segments.json>", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-ios-template schema", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-render drawio <plan.json> --output <diagram.drawio>", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-render drawio <plan.json> --group-by vlan --output <diagram.drawio>", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-render diagram-audit <plan.json> --output <diagram-audit.json>", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-render verification-plan <plan.json> --format markdown --output <verification.md>", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-render svg <plan.json> --title <title> --legend --output <diagram.svg>", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-render bundle <plan.json> --output-dir <render-dir> --basename topology --preset report", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-render bundle <plan.json> --output-dir <render-dir> --basename topology --formats svg,drawio,html,markdown,summary,diagram-audit,verification-json,verification-md --title <title> --legend", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-mcp --list-tools", data["recommended_workflow"])
        self.assertIn("pt-reverse/bin/pt730-mcp  # stdio MCP server; live tools require allow_live=true", data["recommended_workflow"])
        self.assertIn("MCP pt730_schema exposes template/ip_plan/compose/config_plan/pipeline/lab/ios_template input schemas", data["recommended_workflow"])
        self.assertIn("MCP pt730_template_lan_star/pt730_template_wireless_lan/pt730_template_vlan_router_on_stick/pt730_template_switching_lab/pt730_template_server_services/pt730_template_edge_security/pt730_template_router_ring/pt730_template_wan_ring/pt730_template_campus/pt730_template_redundant_campus/pt730_template_enterprise_edge expose full template CLI options including layout_style/no_layout/compact", data["recommended_workflow"])
        self.assertIn("MCP pt730_ip_plan_campus/pt730_compose_campus/pt730_pipeline_campus expose compact and layout_style workflow controls", data["recommended_workflow"])
        self.assertIn("MCP pt730_render exposes visual theme/title/legend/link label/model label/group_by controls for SVG, draw.io, HTML, and Mermaid where supported", data["recommended_workflow"])
        self.assertIn("MCP pt730_render and pt730_render_bundle expose preset=report for paper theme, auto grouping, legend, hidden link labels, diagram-audit, and verification-plan bundle defaults", data["recommended_workflow"])
        self.assertIn("MCP pt730_render_bundle creates multi-format SVG/draw.io/HTML/Markdown/summary/course-audit/diagram-audit/verification bundles with a manifest in one offline call", data["recommended_workflow"])
        self.assertIn("MCP pt730_verification_plan creates JSON or Markdown live/manual validation checklists from topology JSON without contacting Packet Tracer", data["recommended_workflow"])
        self.assertIn("MCP pt730_lab_template creates topology/safety/render/configs/manifest lab bundles from one template spec JSON", data["recommended_workflow"])
        self.assertIn("MCP pt730_lab_plan creates topology/safety/render/configs/manifest lab bundles from an existing topology plan JSON", data["recommended_workflow"])
        self.assertIn("MCP pt730_lab_report creates a Markdown coursework/deliverable index from a lab bundle manifest.json", data["recommended_workflow"])
        self.assertIn("MCP pt730_layout exposes canvas_width/canvas_height/spacing_x/spacing_y/margin/compact layout controls", data["recommended_workflow"])
        self.assertIn("MCP pt730_config_plan_campus/pt730_export_configs expose ios_only/compact/source config export controls", data["recommended_workflow"])
        self.assertIn("MCP pt730_catalog exposes devices/device/ports/modules/module/cables/infer_cable/aliases", data["recommended_workflow"])
        self.assertIn("MCP pt730_safety_js and pt730_safety_policy expose JavaScript safety checks and policy", data["recommended_workflow"])
        self.assertIn("MCP pt730_live_ios/pt730_live_pc_static/pt730_live_term/pt730_live_ping/pt730_live_server_inspect support dry_run=true command previews", data["recommended_workflow"])
        self.assertIn("MCP pt730_live_pc_inspect/pt730_live_pc_dhcp/pt730_live_server_service/pt730_live_server_dns_add/pt730_live_server_ftp_add/pt730_live_server_ftp_remove/pt730_live_server_email_add/pt730_live_server_email_remove/pt730_live_server_ntp_config/pt730_live_server_syslog_config/pt730_live_server_dhcp_config/pt730_live_ftp/pt730_live_sim support dry_run=true command previews", data["recommended_workflow"])
        self.assertIn("MCP pt730_topo_summarize_query/pt730_topo_export expose saved-query summarization/export; live export requires allow_live=true", data["recommended_workflow"])
        self.assertIn("MCP pt730_models_manifest/pt730_models_queue/pt730_models_probe_plan/pt730_models_validate/pt730_models_validate_batch/pt730_models_record expose model validation workflows; record requires allow_write=true", data["recommended_workflow"])
        self.assertIn("MCP pt730_live_app/pt730_live_bridge/pt730_live_launch/pt730_live_recover support dry_run=true command previews for lifecycle operations", data["recommended_workflow"])
        self.assertIn("MCP pt730_live_eval/pt730_live_smoke support dry_run=true command previews and require allow_live=true for live execution", data["recommended_workflow"])

    def test_table_output_is_human_readable(self) -> None:
        result = self.run_cmd("--table")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("Offline tools", result.stdout)
        self.assertIn("Live tools", result.stdout)

    def test_compact_output_is_machine_readable_without_indentation(self) -> None:
        result = self.run_cmd("--compact")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertNotIn("\n  ", result.stdout)
        data = json.loads(result.stdout)
        self.assertIn("wan_ring", data["template_features"])
        self.assertIn("wireless_lan", data["template_features"])
        self.assertIn("vlan_router_on_stick", data["template_features"])
        self.assertIn("switching_lab", data["template_features"])
        self.assertIn("server_services", data["template_features"])
        self.assertIn("edge_security", data["template_features"])
        self.assertIn("router_dhcp_pools", data["template_features"])


if __name__ == "__main__":
    unittest.main()
